name: Build Next.js web application

on: push

jobs:
  build-project:
      name: Build Project
      runs-on: Windows-Latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: NPM Download
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload static site content
        uses: actions/upload-artifact@v3
        with:
          name: Beta
          path:
